/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    // Strictly geometric: ALL corners are 0px per the Atelier Heritage design system.
    borderRadius: {
      none: "0px",
      DEFAULT: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      "3xl": "0px",
      full: "0px",
    },
    extend: {
      colors: {
        paper: "#F9F9F7",
        surface: "#f9f9f7",
        obsidian: "#0D0D0D",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e6e1df",
        "tertiary-container": "#1d1b1a",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fddeb5",
        "secondary-fixed-dim": "#e0c29b",
        "on-surface-variant": "#444748",
        "on-primary-fixed": "#1c1b1b",
        "on-surface": "#1a1c1b",
        "inverse-primary": "#c9c6c5",
        "surface-container-low": "#f4f4f2",
        "primary-container": "#1c1b1b",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        graphite: "#262626",
        "outline-variant": "#c4c7c7",
        secondary: "#715b3b",
        "inverse-on-surface": "#f1f1ef",
        outline: "#747878",
        "on-secondary-fixed": "#281802",
        "on-secondary-container": "#786140",
        "bronze-accent": "#BFA37E",
        "surface-container-high": "#e8e8e6",
        "tertiary-fixed-dim": "#cac6c3",
        "on-secondary-fixed-variant": "#584325",
        "surface-container-highest": "#e2e3e1",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#484645",
        background: "#f9f9f7",
        "on-primary-container": "#858383",
        "on-primary": "#ffffff",
        "surface-variant": "#e2e3e1",
        "surface-tint": "#5f5e5e",
        "on-tertiary-fixed": "#1d1b1a",
        "on-primary-fixed-variant": "#474646",
        "silver-subtle": "#E5E5E5",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c9c6c5",
        tertiary: "#000000",
        "surface-bright": "#f9f9f7",
        "secondary-fixed": "#fddeb5",
        "on-tertiary-container": "#868381",
        "surface-dim": "#dadad8",
        "inverse-surface": "#2f3130",
        "on-background": "#1a1c1b",
        primary: "#000000",
        "surface-container": "#eeeeec",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "pb-safe": "env(safe-area-inset-bottom)",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        headline: ["EB Garamond", "serif"],
        body: ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "price-display": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "price-display": ["20px", { lineHeight: "1.0", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
      },
      transitionTimingFunction: {
        "out-soft": "cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
  },
  plugins: [],
};
